# 02- Feature Engineering

## Objectif Bloc 5
Construction des variables exploitables pour le modèle.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../01_Data/raw/data.csv")

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())
df["Churn"] = df["Churn"].map({"No": 0, "Yes": 1})

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

## Interprétation
La cible est transformée en binaire et TotalCharges est convertie en numérique.

In [2]:
df["avg_charge_per_tenure"] = df["MonthlyCharges"] / df["tenure"].replace(0, 1)
df["has_fiber"] = (df["InternetService"] == "Fiber optic").astype(int)
df["is_month_to_month"] = (df["Contract"] == "Month-to-month").astype(int)
df["has_online_security"] = (df["OnlineSecurity"] == "Yes").astype(int)
df["has_tech_support"] = (df["TechSupport"] == "Yes").astype(int)

df[[
    "avg_charge_per_tenure",
    "has_fiber",
    "is_month_to_month",
    "has_online_security",
    "has_tech_support",
    "Churn"
]].head()

,avg_charge_per_tenure,has_fiber,is_month_to_month,has_online_security,has_tech_support,Churn
0,29.850,0,1,0,0,0
1,1.675,0,0,1,0,0
2,26.925,0,1,1,0,1
3,0.940,0,0,1,1,0
4,35.350,1,1,0,0,1

## Interprétation
Ces variables traduisent des facteurs métier : engagement, service, assistance, sécurité et facturation.

In [3]:
df.to_csv("../01_Data/processed/churn_features.csv", index=False)
print("Dataset enrichi sauvegardé.")

Dataset enrichi sauvegardé.